-- Mock seed data was removed.
-- Create the first account from the signup page. That account becomes the administrator.
-- Every later record is saved by the app into Supabase. Do not insert sample patients.
